#include<stdio.h>
#include<windows.h>
void main(){
	printf("男：你穿秋裤了吗?\n");
	Sleep(3000);
	printf("女：我没穿裤子\n");
		Sleep(3000);
	printf("男：我有条绿裤子，你要吗？\n");
		Sleep(3000);
	printf("女：我喜欢红色的\n");
		Sleep(3000);
	printf("男：红色的我只有内裤\n");
		Sleep(3000);
	printf("女：我不喜欢穿内裤\n");
		Sleep(3000);
	printf("男：我内裤都是反穿的\n");
		Sleep(3000);
	printf("女：你太有品味了\n");
}
